### PR TITLE
ADD kubeadm-DO flavor:

### PR DESCRIPTION
**Pull request by gmlp**
Include all terraform and packer definitions to
bring up a k8s cluster on DO

TODO:

- [x] Add CNI
- [x] Add DefaultStorageClass(rook,local)

### CODE REVIEW

**Comment by vfarcic** [comment]
Just tested it and it works like a charm.

I few things that might improve it...

If we add something like S3, we could store the token there and have everything as a single `apply` command. Something like:

1. Create the first master
2. Store the token an external drive (DO Spaces?)
3. Create the rest of the nodes
4. Use the token from the external drive to join the master

Another thing would be the ability to create additional masters (3 in total) as well as short instructions on how to add more workers. Something like "start with one, add one more".


I made a few minor changes (mostly formatting). The only addition (for now) are the commands that will export kubeconfig outside the cluster. It's in https://github.com/vfarcic/k8s-specs/commit/0eca91f1084fdcf31680f4537a3ab3940f8bbd51

**Comment by gmlp** [comment]
@vfarcic,
 Thank you for your feedback. I will work on these improvements.

**Comment by vfarcic** [comment]
First of all, sorry for the delay on my side. I finally got time to go through it again and I noticed that `kube-dns` is not working. That's probably the reason why the status of the nodes is `NotReady`. Can you look into it as well?

**Comment by gmlp** [comment]
Hi Viktor, sure. I notice in k8s docs this " The network must be deployed before any applications. Also, CoreDNS will not start up before a network is installed. kubeadm only supports Container Network Interface (CNI) based networks (and does not support kubenet)."
 https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/
I did a test with Flannel and It worked. I will include it. Also, I need to create a default Storage Class

**Comment by gmlp** [comment]
Hi Viktor, in this PR I have included Flannel.
https://github.com/vfarcic/k8s-specs/pull/8
Regards

**Pull request merged**
