### PR TITLE
REF flavor-kubeadm-do

### PR DESCRIPTION
**Pull request by gmlp**
- Add Flannel cni
- Remove unused templates
- Store token in DO spaces. PR: https://github.com/vfarcic/k8s-specs/pull/6

 output:

NAME         STATUS    ROLES     AGE       VERSION
k8s-master   Ready     master    24m       v1.9.7
k8s-node-1   Ready     <none>    20m       v1.9.7
k8s-node-2   Ready     <none>    20m       v1.9.7

### CODE REVIEW

**Comment by gmlp** [comment]
Hi @vfarcic , can you give me your feedback?
Regards.

**Comment by vfarcic** [comment]
@gmlp I don't think I'll be able to go through it before the weekend. I hope that's OK.

**Comment by vfarcic** [comment]
Can we use Terraform to create a Space for storing cluster state instead of creating it manually and assigning it to `TF_VAR_do_space` env. var.?

**Comment by vfarcic** [comment]
It works like a charm. I think that the next step is to think about storage. We should set up a default StorageClass.

**Comment by gmlp** [comment]
Hi @vfarcic , the space name could be passed through terraform variable?

**Comment by vfarcic** [comment]
I was thinking that it would be nice to create a Space as part of Terraform config. Do you think that would make sense and is doable?

**Comment by gmlp** [comment]
@vfarcic , Make perfect sense.  I 'll work on that today.
Regards.

**Pull request merged**
